# Generated by Django 3.2.7 on 2021-10-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('Otype', models.CharField(max_length=100, null=True)),
                ('Csize', models.IntegerField(null=True)),
                ('Place', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
